const snippets = {
  python: [
    "def",
    "top_words(text, n=3):",
    "\n",
    "counts = {}",
    "\n",
    "for word in text.lower().split():",
    "\n",
    "counts[word] = counts.get(word, 0) + 1",
    "\n",
    "return sorted(counts.items(), key=lambda x: x[1], reverse=True)[:n]",
  ],

  javascript: [
    "const",
    "fetchWithRetry = async (url, retries = 3) => {",
    "\n",
    "for (let i = 0; i < retries; i++) {",
    "\n",
    "try {",
    "\n",
    "const res = await fetch(url);",
    "\n",
    "if (!res.ok) throw new Error('Bad response');",
    "\n",
    "return await res.json();",
    "\n",
    "} catch (e) {",
    "\n",
    "if (i === retries - 1) throw e;",
    "\n",
    "await new Promise(r => setTimeout(r, 500));",
    "\n",
    "}",
    "\n",
    "}",
    "\n",
    "}",
  ],

  html: [
    '<form id="todoForm">',
    "\n",
    '<input type="text" id="task" placeholder="New task" />',
    "\n",
    '<button type="submit">Add</button>',
    "\n",
    "</form>",
    "\n",
    '<ul id="list"></ul>',
    "\n",
    "<script>",
    "\n",
    "document.getElementById('todoForm').onsubmit = e => {",
    "\n",
    "e.preventDefault();",
    "\n",
    "const li = document.createElement('li');",
    "\n",
    "li.textContent = task.value;",
    "\n",
    "list.appendChild(li);",
    "\n",
    "};",
    "\n",
    "</script>",
  ],

  java: [
    "import java.util.*;",
    "\n",
    "class LRUCache {",
    "\n",
    "private final int cap;",
    "\n",
    "private LinkedHashMap<Integer, Integer> map;",
    "\n",
    "LRUCache(int cap) {",
    "\n",
    "this.cap = cap;",
    "\n",
    "map = new LinkedHashMap<>(cap, 0.75f, true) {",
    "\n",
    "protected boolean removeEldestEntry(Map.Entry<Integer, Integer> e) {",
    "\n",
    "return size() > LRUCache.this.cap;",
    "\n",
    "}",
    "\n",
    "};",
    "\n",
    "}",
    "\n",
    "}",
  ],

  cpp: [
    "#include <vector>",
    "\n",
    "#include <algorithm>",
    "\n",
    "int longestIncreasingSubsequence(std::vector<int> nums) {",
    "\n",
    "std::vector<int> dp;",
    "\n",
    "for (int x : nums) {",
    "\n",
    "auto it = std::lower_bound(dp.begin(), dp.end(), x);",
    "\n",
    "if (it == dp.end()) dp.push_back(x);",
    "\n",
    "else *it = x;",
    "\n",
    "}",
    "\n",
    "return dp.size();",
    "\n",
    "}",
  ],
};

export default snippets;
